# Generated by Django 3.1.6 on 2021-03-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_product_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
