# Generated by Django 3.1.6 on 2021-03-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0009_auto_20210310_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='ShopApp'),
            preserve_default=False,
        ),
    ]
